using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;
using DG.Tweening;  //DOTween‚đŽg‚¤‚Ć‚«‚Í‚±‚Ěusing‚đ“ü‚ę‚é

public class MenuManager : MonoBehaviour
{

    Animator animator;


    void Start()
    {
        animator = GetComponent<Animator>();
    }

    // Update is called once per frame
    void Update()
    {
       
    }

    public void OpenOptionAnim()
    {
        //menu.SetActive(true);
        animator.SetBool("isManu", true);
    }

    public void CloseOptionAnim()
    {
       
        animator.SetBool("isManu", false);
    }

}

